Milestone 1
kalviumcommunity/TravelTryst pull request #2
Opened 2023-09-26 16:47 UTC by Akanksha987

->ER Diagram and Schema Diagram
->Loom Video for the explanation of the PR.
https://www.loom.com/share/46c615b9428e4d598e4037feedfe84e1?sid=d8da5e54-0c91-4da3-9ad0-2d5861c57217
https://www.loom.com/share/5d1938d7c4904d808aea8ede9dcda758?sid=8f8e977c-7512-4b23-8f28-f0c420afc62e

2023-09-26 18:57 UTC, th3c0d3br34ker commented
hey @Akanksha987, thanks for your submission. you have explained your ERD and Schema. 

However, the `GuestStays` entity doesn't fit in this scenario. Please schedule a catchup with me.

2023-09-26 19:30 UTC, Akanksha987 commented
Sure

On Wed, Sep 27, 2023, 00:27 Jainam Desai ***@***.***> wrote:

> hey @Akanksha987 <https://github.com/Akanksha987>, thanks for your
> submission. you have explained your ERD and Schema.
>
> However, the GuestStays entity doesn't fit in this scenario. Please
> schedule a catchup with me.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/kalviumcommunity/TravelTryst/pull/2#issuecomment-1736107494>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A23E4HU6TNXQBFWVML6IQ33X4MQSPANCNFSM6AAAAAA5IA4JVM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-09-27 03:55 UTC, Akanksha987 commented
Hey can you please share your calendar so that I can schedule the catchup

2023-09-27 04:52 UTC, th3c0d3br34ker commented
please schedule [here](https://calendar.kalvium.com/jainam-desai/30min).

2023-09-28 08:46 UTC, th3c0d3br34ker commented
hi @Akanksha987, it seems there were some during the video call from your side.

as i understand, you joined the call and shared your screen, but choose not to respond to my queries. this was continued for 10 mins.

i have no choice but to escalate this issue.

thanks.

2023-09-28 14:05 UTC, Akanksha987 commented
Hey @th3c0d3br34ker  I have updated the ERDiagram and Schema Diagram as per your suggestion.

2023-09-28 17:53 UTC, th3c0d3br34ker requested changes
thanks @Akanksha987, the ERD looks good to go. please consider rechecking the schema.

2023-09-28 17:53 UTC, th3c0d3br34ker commented on Schemas.png
hey @Akanksha987 the connection between `Reservation` and `Room` here seems inconsistent.

the `GuestID` property in `Reservations` is connecting to the `Rooms` entity. please consider to recheck the connections made.

2023-09-29 03:45 UTC, Akanksha987 commented
Can you elaborate it a little bit more so that I can understand the connection between room and reservation?

And GuestId is only connected to the reservation entity not to the room Entity.

2023-09-29 09:17 UTC, th3c0d3br34ker commented
thanks @Akanksha987 for reverting back. the ERD is modified as per the discussion during viva.

however the schema is not consistent with what was discussed.

![image](https://github.com/kalviumcommunity/TravelTryst/assets/60807938/a1744454-4a09-44c0-bd69-f8c8187c72be)

i was referring to the following connections made, in my previous comment.
`GuestID` should link to the `Guest` entity
`RoomID` should link to `Room` entity.


please consider the above points and let me know.

2023-09-29 10:00 UTC, Akanksha987 commented
I think because of the entity table you are confused I will just change the position of the table and do the commit

2023-09-29 14:21 UTC, Akanksha987 commented
Hey @th3c0d3br34ker, I have updated the Schema Diagram can you please check it once.

2023-10-03 09:51 UTC, th3c0d3br34ker approved these changes
thanks @Akanksha987 for the update, its clear now. 

please go ahead and merge the PR.

2023-10-03 09:59 UTC, merged